/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { FunctionComponent, useLayoutEffect, useRef } from "react"

import { GLTF, GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader"
import { useFrame, useLoader } from "react-three-fiber"
import { SkinnedMesh, Bone, MeshStandardMaterial, Group } from "three"
// import { Euler } from "three"

type GLTFResult = GLTF & {
  nodes: {
    hand_anatomy_man: SkinnedMesh
    root: Bone
    ["MCH-hand_ikparentL"]: Bone
    ["MCH-upper_arm_ik_targetparentL"]: Bone
  }
  materials: {
    Material: MeshStandardMaterial
  }
}

function draco(url = "https://www.gstatic.com/draco/v1/decoders/") {
  return (loader: GLTFLoader) => {
    const dracoLoader = new DRACOLoader()
    dracoLoader.setDecoderPath(url)
    loader.setDRACOLoader(dracoLoader)
  }
}

function useGLTF<T>(path: string, useDraco = true): GLTF & T {
  const gltf = useLoader(
    GLTFLoader,
    path,
    useDraco
      ? draco(typeof useDraco === "string" ? useDraco : undefined)
      : undefined
  )
  return gltf as GLTF & T
}

useGLTF.preload = (path: string, useDraco = true) =>
  useLoader.preload(
    GLTFLoader,
    path,
    useDraco
      ? draco(typeof useDraco === "string" ? useDraco : undefined)
      : undefined
  )

interface IProps {
  gltfURL: string
}

const HandModel: FunctionComponent<IProps & JSX.IntrinsicElements["group"]> = ({
  gltfURL,
  ...props
}) => {
  useLayoutEffect(() => void useGLTF.preload(gltfURL), [gltfURL])

  const group = useRef<Group>()
  const { nodes, materials } = useGLTF<GLTFResult>(gltfURL)
  // const eulerRot = useRef<Euler>(new Euler(0, 0, 0))

  useFrame(() =>
    // { clock }
    {
      group.current.rotateY(0.005)
      // group.current.setRotationFromEuler(eulerRot.current)
      // eulerRot.current.y =
      //   ((Math.sin(clock.getElapsedTime()) + 1) / 2) * 2 * Math.PI
    }
  )

  return (
    <group ref={group} {...props}>
      <group rotation={[0, 0.98, 0]} scale={[1.76, 1.76, 1.76]}>
        <group
          position={[0, 2.59, 0]}
          rotation={[0, 1.18, -Math.PI]}
          scale={[0.57, 0.57, 0.57]}
        >
          <primitive object={nodes.root} />
          <primitive object={nodes["MCH-hand_ikparentL"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentL"]} />
          <skinnedMesh
            material={materials.Material}
            geometry={nodes.hand_anatomy_man.geometry}
            skeleton={nodes.hand_anatomy_man.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

export default HandModel
